language: csharp
sudo: required
mono:
  - latest
  - 3.2.8

install: 
- sudo mozroots --import --url https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt --sync

script: 
  - ./build.sh --target "Travis"
    
